### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by Flood1993** [Illedran/NIPSTimeMachine#4]
It would be great to have a `requirements.txt` file so as to easily install all package dependencies.

**Comment by Illedran** [comment]
Agreed! I can prepare a common one with packages that I assume everybody will use in some form or another. You can write here new packages that you need aswell.

**Comment by Informhunter** [comment]
I'm using for now:

- Pandas 
- NumPy
- NLTK
- Sklearn

But I'm not sure, which of those will go to the production phase.
